### PR TITLE
Changes default logger used by blib2to3 Driver

### PR DESCRIPTION
**Pull request by apljungquist**

### CODE REVIEW

**Comment by zsol** [comment]
lgtm, but please add this change to the readme of blib2to3

**Comment by zsol** [comment]
Also maybe consider upstreaming it ;)

**Comment by apljungquist** [comment]
"upstreaming it"?

**Comment by zsol** [comment]
Yes, blib2to3 is a fork of https://github.com/python/cpython/tree/master/Lib/lib2to3

It's a good idea to make changes there as well if they make sense

**Comment by apljungquist** [comment]
Good point, I'll look into it.

**Comment by ambv** [comment]
Thanks! ✨ 🍰 ✨

**Pull request merged**
