### PR TITLE
Add Emacs text editor integration to the README.

### PR DESCRIPTION
**Pull request by proofit404**

### CODE REVIEW

**Comment by ambv** [comment]
Thank you very much for this! But you probably don't want [blackify](https://en.m.wiktionary.org/wiki/blackify) as the name but [blacken](https://en.m.wiktionary.org/wiki/blacken).

**Comment by proofit404** [comment]
Oh, yeah. Sorry. I was named to match [yapfify](https://github.com/JorisE/yapfify) and [isortify](https://github.com/proofit404/isortify) naming schema. Will change.

**Comment by proofit404** [comment]
Fixed.

**Comment by ambv** [comment]
Thanks! ✨ 🍰 ✨

**Pull request merged**
