### PR TITLE
Specify the minimum click version

### PR DESCRIPTION
**Pull request by skorokithakis**

### CODE REVIEW

**Comment by ambv** [comment]
Thank you! You will also want to add this to the Pipfile.

**Comment by skorokithakis** [comment]
Ah, that'll have to wait a few days, I'm afraid... I'm nowhere near a computer 🙁

**Comment by ambv** [comment]
Haha, alright, let's merge this then first. I'll add the Pipfile entry.

**Comment by ambv** [comment]
Thanks! ✨ 🍰 ✨

**Comment by skorokithakis** [comment]
I love you!

**Pull request merged**
