### PR TITLE
The very exact Henry Ford’s quote.

### PR DESCRIPTION
**Pull request by batisteo**

### CODE REVIEW

**Comment by ambv** [comment]
Thanks for your contribution but we'll keep the existing wording :-)

**Comment by batisteo** [comment]
I guess arguing here would be bikeshedding anyway :slightly_smiling_face:

**Comment by batisteo** [comment]
I just though some people in the #118 thread didn’t get the reference of this project name.

**Comment by jgirardet** [comment]
I must say I didn't know this sentence and I now better understand @ambv's state of mind.
your PR wasn't useless for me ;-)

**Comment by ambv** [comment]
Let's keep this as a not very well hidden Easter egg. It's more satisfying when people find out on their own ;-)

**Pull request closed without merging**
